name: update-repo

on:
  schedule:
    - cron: '0 0 * * *'  # Setiap hari pada tengah malam
  push:
    branches:
      - main

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set commit date for each day in 2024
        run: |
          start_date="01-01-2024"
          end_date="30-12-2024"
          current_date=$start_date
          
          while [[ "$current_date" < "$end_date" ]]; do
            # Set the commit date to the current date
            export GIT_AUTHOR_DATE="$current_date"
            export GIT_COMMITTER_DATE="$current_date"
            
            # Modifikasi file yang ingin diupdate
            echo "Last updated on $current_date by Nabildzikrika" > README.md
            echo "Last updated on $current_date by Nabildzikrika" > Dockerfile
            echo "Last updated on $current_date by Nabildzikrika" > LAST_UPDATED
            
            # Commit perubahan
            git config --local user.email "muhammadnbills@gmail.com"
            git config --local user.name "blldzr"
            git add -A
            git commit -m "Update for $current_date"
            
            # Increment ke hari berikutnya
            current_date=$(date -I -d "$current_date + 1 day")
          done

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
